# Form implementation generated from reading ui file 'logIn.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LogInWindow(object):
    def setupUi(self, LogInWindow):
        LogInWindow.setObjectName("LogInWindow")
        LogInWindow.resize(260, 180)
        LogInWindow.setMinimumSize(QtCore.QSize(260, 180))
        LogInWindow.setMaximumSize(QtCore.QSize(260, 180))
        font = QtGui.QFont()
        font.setKerning(False)
        LogInWindow.setFont(font)
        LogInWindow.setStyleSheet("#LogInWindow{\n"
"background-color:#6899D3\n"
"}\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(parent=LogInWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.FrameLogIn = QtWidgets.QFrame(parent=self.centralwidget)
        self.FrameLogIn.setMinimumSize(QtCore.QSize(240, 160))
        self.FrameLogIn.setMaximumSize(QtCore.QSize(240, 160))
        self.FrameLogIn.setStyleSheet("QFrame{\n"
"background: #FFA573;\n"
"border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgba(85, 170, 127, 155);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(85, 170, 127, 135);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(85, 170, 127, 205);\n"
"}\n"
"\n"
"QLabel{\n"
"border: 1px solid transparent;\n"
"}\n"
"\n"
"QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 3px;\n"
"}")
        self.FrameLogIn.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.FrameLogIn.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.FrameLogIn.setObjectName("FrameLogIn")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.FrameLogIn)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.FrameLogIn)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setItalic(False)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LineEditLogin = QtWidgets.QLineEdit(parent=self.FrameLogIn)
        self.LineEditLogin.setMaximumSize(QtCore.QSize(100100, 27))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setItalic(False)
        self.LineEditLogin.setFont(font)
        self.LineEditLogin.setObjectName("LineEditLogin")
        self.gridLayout.addWidget(self.LineEditLogin, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.FrameLogIn)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.FrameLogIn)
        self.label.setMaximumSize(QtCore.QSize(111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.LineEditPassword = QtWidgets.QLineEdit(parent=self.FrameLogIn)
        self.LineEditPassword.setMaximumSize(QtCore.QSize(16777215, 27))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setItalic(False)
        self.LineEditPassword.setFont(font)
        self.LineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.LineEditPassword.setObjectName("LineEditPassword")
        self.gridLayout.addWidget(self.LineEditPassword, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bttnExit = QtWidgets.QPushButton(parent=self.FrameLogIn)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setItalic(False)
        self.bttnExit.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../study/Диплом/icons/4115235-exit-logout-sign-out_114030.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bttnExit.setIcon(icon)
        self.bttnExit.setObjectName("bttnExit")
        self.horizontalLayout.addWidget(self.bttnExit)
        self.bttnLog = QtWidgets.QPushButton(parent=self.FrameLogIn)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setItalic(False)
        self.bttnLog.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../study/Диплом/icons/enter_icon-icons.com_48306.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bttnLog.setIcon(icon1)
        self.bttnLog.setObjectName("bttnLog")
        self.horizontalLayout.addWidget(self.bttnLog)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.FrameLogIn)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        LogInWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(LogInWindow)
        QtCore.QMetaObject.connectSlotsByName(LogInWindow)

    def retranslateUi(self, LogInWindow):
        _translate = QtCore.QCoreApplication.translate
        LogInWindow.setWindowTitle(_translate("LogInWindow", "Аутентификация"))
        self.label_3.setText(_translate("LogInWindow", "Войдите в систему"))
        self.label_2.setText(_translate("LogInWindow", "Пароль"))
        self.label.setText(_translate("LogInWindow", "Логин"))
        self.bttnExit.setText(_translate("LogInWindow", "Выйти"))
        self.bttnLog.setText(_translate("LogInWindow", "Войти"))
