# Form implementation generated from reading ui file 'reg.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_RegWindow(object):
    def setupUi(self, RegWindow):
        RegWindow.setObjectName("RegWindow")
        RegWindow.resize(260, 193)
        RegWindow.setMinimumSize(QtCore.QSize(260, 193))
        RegWindow.setMaximumSize(QtCore.QSize(260, 193))
        RegWindow.setStyleSheet("#RegWindow{\n"
"background-color:#6899D3\n"
"}")
        self.centralwidget = QtWidgets.QWidget(parent=RegWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background: #FFA573;\n"
"border: 2px solid black;\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgba(85, 170, 127, 155);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgba(85, 170, 127, 135);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: rgba(85, 170, 127, 205);\n"
"}\n"
"\n"
"QLabel{\n"
"border: 1px solid transparent;\n"
"}\n"
"\n"
"QLineEdit{\n"
"border: 1px solid black;\n"
"border-radius: 3px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Droid Serif")
        font.setPointSize(17)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.LineEditLogin = QtWidgets.QLineEdit(parent=self.frame)
        self.LineEditLogin.setMinimumSize(QtCore.QSize(0, 35))
        self.LineEditLogin.setMaximumSize(QtCore.QSize(100100, 35))
        font = QtGui.QFont()
        font.setFamily("Droid Serif")
        font.setPointSize(12)
        font.setItalic(False)
        self.LineEditLogin.setFont(font)
        self.LineEditLogin.setObjectName("LineEditLogin")
        self.gridLayout.addWidget(self.LineEditLogin, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setMaximumSize(QtCore.QSize(111, 16777215))
        font = QtGui.QFont()
        font.setFamily("Droid Serif")
        font.setPointSize(14)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Droid Serif")
        font.setPointSize(14)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.LineEditPassword = QtWidgets.QLineEdit(parent=self.frame)
        self.LineEditPassword.setMinimumSize(QtCore.QSize(0, 35))
        self.LineEditPassword.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Droid Serif")
        font.setPointSize(12)
        font.setItalic(False)
        self.LineEditPassword.setFont(font)
        self.LineEditPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.LineEditPassword.setObjectName("LineEditPassword")
        self.gridLayout.addWidget(self.LineEditPassword, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.bttnReg = QtWidgets.QPushButton(parent=self.frame)
        font = QtGui.QFont()
        font.setFamily("Droid Serif")
        font.setPointSize(14)
        font.setItalic(False)
        self.bttnReg.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../study/Диплом/icons/4115235-exit-logout-sign-out_114030.ico"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.bttnReg.setIcon(icon)
        self.bttnReg.setObjectName("bttnReg")
        self.verticalLayout_3.addWidget(self.bttnReg)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        RegWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(RegWindow)
        QtCore.QMetaObject.connectSlotsByName(RegWindow)

    def retranslateUi(self, RegWindow):
        _translate = QtCore.QCoreApplication.translate
        RegWindow.setWindowTitle(_translate("RegWindow", "Регистрация"))
        self.label_3.setText(_translate("RegWindow", "Регистрация в АРМ"))
        self.label.setText(_translate("RegWindow", "Логин"))
        self.label_2.setText(_translate("RegWindow", "Пароль"))
        self.bttnReg.setText(_translate("RegWindow", "Зарегистрироваться"))
